name: termscope
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dartssh2: ^2.11.0
  flutter:
    sdk: flutter
  flutter_pty: ^0.4.2
  flutter_screenutil: ^5.9.3
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  xterm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
